<?php

class format_ttf_LangMacintosh extends Enum {
	public static $Arabic;
	public static $Armenian;
	public static $Bengali;
	public static $Burmese;
	public static $Devanagari;
	public static $Geez;
	public static $Georgian;
	public static $Greek;
	public static $Gujarati;
	public static $Gurmukhi;
	public static $Hebrew;
	public static $Japanese;
	public static $Kannada;
	public static $Khmer;
	public static $Korean;
	public static $Laotian;
	public static $Malayalam;
	public static $Mongolian;
	public static $Oriya;
	public static $RSymbol;
	public static $Roman;
	public static $Russian;
	public static $SimplifiedChinese;
	public static $Sindhi;
	public static $Sinhalese;
	public static $Slavic;
	public static $Tamil;
	public static $Telugu;
	public static $Thai;
	public static $Tibetan;
	public static $TraditionalChinese;
	public static $Uninterpreted;
	public static $Vietnamese;
	public static $__constructors = array(4 => 'Arabic', 24 => 'Armenian', 13 => 'Bengali', 19 => 'Burmese', 9 => 'Devanagari', 28 => 'Geez', 23 => 'Georgian', 6 => 'Greek', 11 => 'Gujarati', 10 => 'Gurmukhi', 5 => 'Hebrew', 1 => 'Japanese', 16 => 'Kannada', 20 => 'Khmer', 3 => 'Korean', 22 => 'Laotian', 17 => 'Malayalam', 27 => 'Mongolian', 12 => 'Oriya', 8 => 'RSymbol', 0 => 'Roman', 7 => 'Russian', 25 => 'SimplifiedChinese', 31 => 'Sindhi', 18 => 'Sinhalese', 29 => 'Slavic', 14 => 'Tamil', 15 => 'Telugu', 21 => 'Thai', 26 => 'Tibetan', 2 => 'TraditionalChinese', 32 => 'Uninterpreted', 30 => 'Vietnamese');
	}
format_ttf_LangMacintosh::$Arabic = new format_ttf_LangMacintosh("Arabic", 4);
format_ttf_LangMacintosh::$Armenian = new format_ttf_LangMacintosh("Armenian", 24);
format_ttf_LangMacintosh::$Bengali = new format_ttf_LangMacintosh("Bengali", 13);
format_ttf_LangMacintosh::$Burmese = new format_ttf_LangMacintosh("Burmese", 19);
format_ttf_LangMacintosh::$Devanagari = new format_ttf_LangMacintosh("Devanagari", 9);
format_ttf_LangMacintosh::$Geez = new format_ttf_LangMacintosh("Geez", 28);
format_ttf_LangMacintosh::$Georgian = new format_ttf_LangMacintosh("Georgian", 23);
format_ttf_LangMacintosh::$Greek = new format_ttf_LangMacintosh("Greek", 6);
format_ttf_LangMacintosh::$Gujarati = new format_ttf_LangMacintosh("Gujarati", 11);
format_ttf_LangMacintosh::$Gurmukhi = new format_ttf_LangMacintosh("Gurmukhi", 10);
format_ttf_LangMacintosh::$Hebrew = new format_ttf_LangMacintosh("Hebrew", 5);
format_ttf_LangMacintosh::$Japanese = new format_ttf_LangMacintosh("Japanese", 1);
format_ttf_LangMacintosh::$Kannada = new format_ttf_LangMacintosh("Kannada", 16);
format_ttf_LangMacintosh::$Khmer = new format_ttf_LangMacintosh("Khmer", 20);
format_ttf_LangMacintosh::$Korean = new format_ttf_LangMacintosh("Korean", 3);
format_ttf_LangMacintosh::$Laotian = new format_ttf_LangMacintosh("Laotian", 22);
format_ttf_LangMacintosh::$Malayalam = new format_ttf_LangMacintosh("Malayalam", 17);
format_ttf_LangMacintosh::$Mongolian = new format_ttf_LangMacintosh("Mongolian", 27);
format_ttf_LangMacintosh::$Oriya = new format_ttf_LangMacintosh("Oriya", 12);
format_ttf_LangMacintosh::$RSymbol = new format_ttf_LangMacintosh("RSymbol", 8);
format_ttf_LangMacintosh::$Roman = new format_ttf_LangMacintosh("Roman", 0);
format_ttf_LangMacintosh::$Russian = new format_ttf_LangMacintosh("Russian", 7);
format_ttf_LangMacintosh::$SimplifiedChinese = new format_ttf_LangMacintosh("SimplifiedChinese", 25);
format_ttf_LangMacintosh::$Sindhi = new format_ttf_LangMacintosh("Sindhi", 31);
format_ttf_LangMacintosh::$Sinhalese = new format_ttf_LangMacintosh("Sinhalese", 18);
format_ttf_LangMacintosh::$Slavic = new format_ttf_LangMacintosh("Slavic", 29);
format_ttf_LangMacintosh::$Tamil = new format_ttf_LangMacintosh("Tamil", 14);
format_ttf_LangMacintosh::$Telugu = new format_ttf_LangMacintosh("Telugu", 15);
format_ttf_LangMacintosh::$Thai = new format_ttf_LangMacintosh("Thai", 21);
format_ttf_LangMacintosh::$Tibetan = new format_ttf_LangMacintosh("Tibetan", 26);
format_ttf_LangMacintosh::$TraditionalChinese = new format_ttf_LangMacintosh("TraditionalChinese", 2);
format_ttf_LangMacintosh::$Uninterpreted = new format_ttf_LangMacintosh("Uninterpreted", 32);
format_ttf_LangMacintosh::$Vietnamese = new format_ttf_LangMacintosh("Vietnamese", 30);
